theme: jekyll-theme-slate
title: Discovering Chaos in Prime Numbers
description: Technicalâ€“historical record of a spectral phenomenon in arithmetic.
show_downloads: true
google_analytics: G-58K8Z0MGPK
